name: variable1
on: workflow_dispatch

env: 
  variable: test1

jobs:
  build_1:
    runs-on: ubuntu-latest
    env:
      variable: test2
    steps:
    - name: Step 1
      run: |
        echo "Run Step 1, varibale : $variable"
    - name: Step 2
      run: |
        echo "Run Step 2, varibale : $variable"
      env:
        varibale: test3
    - name: Step 3
      run: |
        echo "Run Step 3, varibale : $variable"
  build_2:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: |
        echo "Run Step 1, varibale : $variable"
